### ISSUE TITLE
Allow image to fade-in into the website when lazyloaded

### ISSUE THREAD

**Issue by Nazrinn** [Codeinwp/optimole-wp#623]
### What problem does this address?

When I browse my website, seeing images just "appear" is often a bit jarring.

### What is your proposed solution?

Add a CSS class to images that are being lazyloaded, similar to LiteSpeed Cache, allowing to add a little bit of CSS to the site to give your images an animation of your choice. Fade-in example:

```css
/* PART 1 - Before Lazy Load */
img[data-lazyloaded]{
    opacity: 0;
    will-change: opacity;  
}

/* PART 2 - Upon Lazy Load */
img.litespeed-loaded{
    -webkit-transition: all .25s ease;
    -moz-transition: all .25s ease;
    transition: all .25s ease;
    opacity: 1;
}
```

OR

Give simple animation options for the user to choose via a drop-down in Optimole's options.

### Will this feature require documentation? (Optional)

Yes, it requires documentation.

**Comment by abaicus** [comment]
Hello @Nazrinn,

Thank you for the feedback and the idea! We'll consider adding more presets for a future release for sure!

Optimole already has an animation using a blur filter, which is removed when the image is loaded. 

<details>

<summary>Example of the current animation</summary>

![bh](https://github.com/Codeinwp/optimole-wp/assets/15010186/7f70e7df-26f2-4b86-a4c2-3a5774bdd182)

</details>


However, you should still be able to add custom animations to this based on the image's attributes during the lazyloading process, similar to how you do it with LiteSpeed Cache. You can use the following selectors:

```css
/* PART 1 - Before Lazy Load */
img[data-opt-src]:not([data-opt-lazy-loaded]) {
    opacity: 0;
    will-change: opacity;  
}

/* PART 2 - Upon Lazy Load */
img[data-opt-lazy-loaded] {
    -webkit-transition: all .25s ease;
    -moz-transition: all .25s ease;
    transition: all .25s ease;
    opacity: 1;
}
```

I hope the above helps!
